exports.which = ['Instagram',
    'Facebook',
    'Twitter',
    'Snapchat',
    'Tiktok',
    'Youtube',
    'Linkedin',
    'Github',
    'Behance',
    'Twitch',
    'Email',
    'Blog',
    'Store',
    'Portfolio',
    'Personal/Company Website',
    'Other'
]

exports.preURL = {
    'Instagram': 'https://www.instagram.com/',
    'Facebook': 'https://www.facebook.com/',
    'Twitter': 'https://twitter.com/',
    'Snapchat': 'https://story.snapchat.com/s/',
    'Tiktok': 'https://www.tiktok.com/@',
    'Youtube': 'https://www.youtube.com/channel/',
    'Linkedin': 'https://www.linkedin.com/in/',
    'Github': 'https://github.com/',
    'Behance': 'https://www.behance.net/',
    'Twitch': 'https://www.twitch.tv/',
    'Email': 'mailto:'
}

exports.icone = {
    'Instagram': 'fab fa-instagram',
    'Facebook' : 'fab fa-facebook-f',
    'Twitter' : 'fab fa-twitter',
    'Snapchat' : 'fab fa-snapchat-ghost',
    'Tiktok' : 'fab fa-tiktok',
    'Youtube' : 'fab fa-youtube',
    'Linkedin' : 'fab fa-linkedin-in',
    'Github' : 'fab fa-github',
    'Behance' : 'fab fa-behance-square',
    'Twitch' : 'fab fa-twitch',
    'Email' : 'fas fa-at',
    'Blog' : 'fab fa-blogger-b',
    'Store' : 'fas fa-store-alt',
    'Portfolio' : 'fas fa-user-circle',
    'Personal/Company Website' : 'fab fa-wordpress-simple',
    'Other' : 'fas fa-feather',
}