exports.which = {
    'instagram' : "models.contact.which.enum.values.instagram",
    'facebook' : "models.contact.which.enum.values.facebook",
    'twitter' : "models.contact.which.enum.values.twitter",
    'snapchat' : "models.contact.which.enum.values.snapchat",
    'tiktok' : "models.contact.which.enum.values.tiktok",
    'vk' : "models.contact.which.enum.values.vk",
    'youtube' : "models.contact.which.enum.values.youtube",
    'linkedin' : "models.contact.which.enum.values.linkedin",
    'github' : "models.contact.which.enum.values.github",
    'medium' : "models.contact.which.enum.values.medium",
    'behance' : "models.contact.which.enum.values.behance",
    'twitch' : "models.contact.which.enum.values.twitch",
    'email' : "models.contact.which.enum.values.email",
    'whatsapp' : "models.contact.which.enum.values.whatsapp",
    'blog' : "models.contact.which.enum.values.blog",
    'store' : "models.contact.which.enum.values.store",
    'portfolio' : "models.contact.which.enum.values.portfolio",
    'website' : "models.contact.which.enum.values.website",
    'other' : "models.contact.which.enum.values.other"
}
/* 
exports.which = ['Instagram',
    'Facebook',
    'Twitter',
    'Snapchat',
    'Tiktok',
    'Youtube',
    'Linkedin',
    'Github',
    'Behance',
    'Twitch',
    'Email',
    'Whatsapp',
    'Blog',
    'Store',
    'Portfolio',
    'Personal/Company Website',
    'Other'
]
*/

exports.preURL = {
    'instagram': 'https://www.instagram.com/',
    'facebook': 'https://www.facebook.com/',
    'twitter': 'https://twitter.com/',
    'snapchat': 'https://story.snapchat.com/s/',
    'tiktok': 'https://www.tiktok.com/@',
    'vk' : 'https://vk.com/',
    'youtube': 'https://www.youtube.com/channel/',
    'linkedin': 'https://www.linkedin.com/in/',
    'github': 'https://github.com/',
    'medium' : 'https://medium.com/@',
    'behance': 'https://www.behance.net/',
    'twitch': 'https://www.twitch.tv/',
    'email': 'mailto:',
    'whatsapp' : 'tel:'
}

exports.icone = {
    'instagram': 'fab fa-instagram',
    'facebook' : 'fab fa-facebook',
    'twitter' : 'fab fa-twitter',
    'snapchat' : 'fab fa-snapchat-ghost',
    'tiktok' : 'fab fa-tiktok',
    'vk' : 'fab fa-vk',
    'youtube' : 'fab fa-youtube',
    'linkedin' : 'fab fa-linkedin-in',
    'github' : 'fab fa-github',
    'medium' : 'fab fa-medium-m',
    'behance' : 'fab fa-behance',
    'twitch' : 'fab fa-twitch',
    'email' : 'fas fa-at at-icone',
    'whatsapp' : 'fab fa-whatsapp',
    'blog' : 'fab fa-blogger-b',
    'store' : 'fas fa-store',
    'portfolio' : 'fas fa-user-circle',
    // 'Personal/Company Website' : 'fab fa-wordpress-simple',
    'website' : 'fas fa-globe webSite',
    'other' : 'fas fa-feather other'
}